package model;

/**
 * 
 * 
 * Constructor, getters and setters were autogenerated by NetBeans. 
 * 
 * @author  Franklin D. Worrell
 * @version 22 April 2017
 */
public class Company {
    private String companyID; 
    private String companyName; 
    private String cStreetNo; 
    private String cStreetName; 
    private String cUnitNo; 
    private String cCity; 
    private String cState;
    private String cZip; 
    private String companyWebsite; 
    private String primarySector;     

    public Company(String companyID, String companyName, String cStreetNo, 
                   String cStreetName, String cUnitNo, String cCity, 
                   String cState, String cZip, String companyWebsite, 
                   String primarySector) {
        this.companyID = companyID;
        this.companyName = companyName;
        this.cStreetNo = cStreetNo;
        this.cStreetName = cStreetName;
        this.cUnitNo = cUnitNo;
        this.cCity = cCity;
        this.cState = cState;
        this.cZip = cZip;
        this.companyWebsite = companyWebsite;
        this.primarySector = primarySector;
    } // end constructor

    /**
     * @return the companyID
     */
    public String getCompanyID() {
        return companyID;
    }

    /**
     * @param companyID the companyID to set
     */
    public void setCompanyID(String companyID) {
        this.companyID = companyID;
    }

    /**
     * @return the companyName
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * @param companyName the companyName to set
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * @return the cStreetNo
     */
    public String getcStreetNo() {
        return cStreetNo;
    }

    /**
     * @param cStreetNo the cStreetNo to set
     */
    public void setcStreetNo(String cStreetNo) {
        this.cStreetNo = cStreetNo;
    }

    /**
     * @return the cStreetName
     */
    public String getcStreetName() {
        return cStreetName;
    }

    /**
     * @param cStreetName the cStreetName to set
     */
    public void setcStreetName(String cStreetName) {
        this.cStreetName = cStreetName;
    }

    /**
     * @return the cUnitNo
     */
    public String getcUnitNo() {
        return cUnitNo;
    }

    /**
     * @param cUnitNo the cUnitNo to set
     */
    public void setcUnitNo(String cUnitNo) {
        this.cUnitNo = cUnitNo;
    }

    /**
     * @return the cCity
     */
    public String getcCity() {
        return cCity;
    }

    /**
     * @param cCity the cCity to set
     */
    public void setcCity(String cCity) {
        this.cCity = cCity;
    }

    /**
     * @return the cState
     */
    public String getcState() {
        return cState;
    }

    /**
     * @param cState the cState to set
     */
    public void setcState(String cState) {
        this.cState = cState;
    }

    /**
     * @return the cZip
     */
    public String getcZip() {
        return cZip;
    }

    /**
     * @param cZip the cZip to set
     */
    public void setcZip(String cZip) {
        this.cZip = cZip;
    }

    /**
     * @return the companyWebsite
     */
    public String getCompanyWebsite() {
        return companyWebsite;
    }

    /**
     * @param companyWebsite the companyWebsite to set
     */
    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite;
    }

    /**
     * @return the primarySector
     */
    public String getPrimarySector() {
        return primarySector;
    }

    /**
     * @param primarySector the primarySector to set
     */
    public void setPrimarySector(String primarySector) {
        this.primarySector = primarySector;
    }
} // end class Company
