/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * 
 * Constructor, getters, and setters generated by NetBeans. 
 * 
 * @author fdworrell
 */
public class Job {
    private String jobCode; 
    private String companyID; 
    private String empMode; 
    private String payType; 
    private String jobTitle; 
    private String jobDescription; 

    public Job(String jobCode, String companyID, String empMode, String payType, 
               String jobTitle, String jobDescription) {
        this.jobCode = jobCode;
        this.companyID = companyID;
        this.empMode = empMode;
        this.payType = payType;
        this.jobTitle = jobTitle;
        this.jobDescription = jobDescription;
    } // end Constructor

    /**
     * @return the jobCode
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * @param jobCode the jobCode to set
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    /**
     * @return the companyID
     */
    public String getCompanyID() {
        return companyID;
    }

    /**
     * @param companyID the companyID to set
     */
    public void setCompanyID(String companyID) {
        this.companyID = companyID;
    }

    /**
     * @return the empMode
     */
    public String getEmpMode() {
        return empMode;
    }

    /**
     * @param empMode the empMode to set
     */
    public void setEmpMode(String empMode) {
        this.empMode = empMode;
    }

    /**
     * @return the payType
     */
    public String getPayType() {
        return payType;
    }

    /**
     * @param payType the payType to set
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * @return the jobTitle
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * @param jobTitle the jobTitle to set
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    /**
     * @return the jobDescription
     */
    public String getJobDescription() {
        return jobDescription;
    }

    /**
     * @param jobDescription the jobDescription to set
     */
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }
} // end class Job
