package model;

/**
 *
 * 
 * Constructor, getters, and setters generated by NetBeans. 
 * 
 * @author  Franklin D. Worrell
 * @version 23 April 2017
 */
public class JobCategory {
    private String SOCCode; 
    private String SOCDescription; 

    public JobCategory(String SOCCode, String SOCDescription) {
        this.SOCCode = SOCCode;
        this.SOCDescription = SOCDescription;
    }

    /**
     * @return the SOCCode
     */
    public String getSOCCode() {
        return SOCCode;
    }

    /**
     * @param SOCCode the SOCCode to set
     */
    public void setSOCCode(String SOCCode) {
        this.SOCCode = SOCCode;
    }

    /**
     * @return the SOCDescription
     */
    public String getSOCDescription() {
        return SOCDescription;
    }

    /**
     * @param SOCDescription the SOCDescription to set
     */
    public void setSOCDescription(String SOCDescription) {
        this.SOCDescription = SOCDescription;
    }
} // end class JobCategory
