package model;

/**
 * 
 * 
 * Getters and setters were autogenerated by Netbeans. 
 * 
 * @author  Franklin D. Worrell
 * @version 22 April 2017
 */
public class Person {
    private String personID; 
    private String firstName; 
    private String middleName; 
    private String lastName; 
    private String pStreetNo; 
    private String pStreetName; 
    private String pUnitNo;
    private String pCity; 
    private String pState; 
    private String pZip; 
    private String email; 
    private String gender; 
    
    public Person(String personID, String firstName, String middleName, 
                  String lastName, String pStreetNo, String pStreetName, 
                  String pUnitNo, String pCity, String pState, String pZip, 
                  String email, String gender) {
        this.personID = personID; 
        this.firstName = firstName; 
        this.middleName = middleName; 
        this.lastName = lastName; 
        this.pStreetNo = pStreetNo; 
        this.pStreetName = pStreetName; 
        this.pUnitNo = pUnitNo;
        this.pCity = pCity; 
        this.pState = pState; 
        this.pZip = pZip; 
        this.email = email; 
        this.gender = gender; 
    } // end constructor

    /**
     * @return the personID
     */
    public String getPersonID() {
        return personID;
    }

    /**
     * @param personID the personID to set
     */
    public void setPersonID(String personID) {
        this.personID = personID;
    }

    /**
     * @return the firstName
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName the firstName to set
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the middleName
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * @param middleName the middleName to set
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * @return the lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName the lastName to set
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the pStreetNo
     */
    public String getpStreetNo() {
        return pStreetNo;
    }

    /**
     * @param pStreetNo the pStreetNo to set
     */
    public void setpStreetNo(String pStreetNo) {
        this.pStreetNo = pStreetNo;
    }

    /**
     * @return the pStreetName
     */
    public String getpStreetName() {
        return pStreetName;
    }

    /**
     * @param pStreetName the pStreetName to set
     */
    public void setpStreetName(String pStreetName) {
        this.pStreetName = pStreetName;
    }

    /**
     * @return the pUnitNo
     */
    public String getpUnitNo() {
        return pUnitNo;
    }

    /**
     * @param pUnitNo the pUnitNo to set
     */
    public void setpUnitNo(String pUnitNo) {
        this.pUnitNo = pUnitNo;
    }

    /**
     * @return the pCity
     */
    public String getpCity() {
        return pCity;
    }

    /**
     * @param pCity the pCity to set
     */
    public void setpCity(String pCity) {
        this.pCity = pCity;
    }

    /**
     * @return the pState
     */
    public String getpState() {
        return pState;
    }

    /**
     * @param pState the pState to set
     */
    public void setpState(String pState) {
        this.pState = pState;
    }

    /**
     * @return the pZip
     */
    public String getpZip() {
        return pZip;
    }

    /**
     * @param pZip the pZip to set
     */
    public void setpZip(String pZip) {
        this.pZip = pZip;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the gender
     */
    public String getGender() {
        return gender;
    }

    /**
     * @param gender the gender to set
     */
    public void setGender(String gender) {
        this.gender = gender;
    }
} // end class Person
